version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ../db:/var/lib/mysql
    container_name: db
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    volumes:
      - ../volume_web:/dashboard/templates
    container_name: web
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      bash -c '
      [ -d ./static ] || python manage.py collectstatic --no-input ;
      python manage.py makemigrations ;
      python manage.py migrate ;
      python manage.py shell < ./utils/init_superuser.py ;
      python manage.py runserver 0.0.0.0:8000'
